/**
 * Filament Spec Label Translations
 *
 * Maps canonical spec IDs to display labels in all 9 supported languages.
 * Used by spec-utils.ts getSpecLabel() for rendering.
 */

import type { FilamentSpecId } from './spec-registry';
import type { SupportedLocale } from '../../i18n/config';

export const specLabels: Record<FilamentSpecId, Record<SupportedLocale, string>> = {
  // ============================================================
  // Basic
  // ============================================================
  material_type: {
    'zh-cn': '材料类型',
    'zh-tw': '材料類型',
    'en': 'Material Type',
    'ja': '材料タイプ',
    'ko': '재료 유형',
    'es': 'Tipo de material',
    'de': 'Materialtyp',
    'fr': 'Type de matériau',
    'it': 'Tipo di materiale',
  },
  diameter: {
    'zh-cn': '直径',
    'zh-tw': '直徑',
    'en': 'Diameter',
    'ja': '直径',
    'ko': '직경',
    'es': 'Diámetro',
    'de': 'Durchmesser',
    'fr': 'Diamètre',
    'it': 'Diametro',
  },
  density: {
    'zh-cn': '密度',
    'zh-tw': '密度',
    'en': 'Density',
    'ja': '密度',
    'ko': '밀도',
    'es': 'Densidad',
    'de': 'Dichte',
    'fr': 'Densité',
    'it': 'Densità',
  },
  melt_flow_index: {
    'zh-cn': '熔融指数',
    'zh-tw': '熔融指數',
    'en': 'Melt Flow Index',
    'ja': 'メルトフローレート',
    'ko': '용융 흐름 지수',
    'es': 'Índice de fluidez',
    'de': 'Schmelzflussindex',
    'fr': 'Indice de fluidité',
    'it': 'Indice di fluidità',
  },
  printability: {
    'zh-cn': '可打印性',
    'zh-tw': '可列印性',
    'en': 'Printability',
    'ja': '印刷のしやすさ',
    'ko': '출력 용이성',
    'es': 'Imprimibilidad',
    'de': 'Druckbarkeit',
    'fr': 'Imprimabilité',
    'it': 'Stampabilità',
  },
  moisture_sensitivity: {
    'zh-cn': '是否易吸湿',
    'zh-tw': '是否易吸濕',
    'en': 'Moisture Sensitivity',
    'ja': '吸湿性',
    'ko': '흡습 민감도',
    'es': 'Sensibilidad a la humedad',
    'de': 'Feuchtigkeitsempfindlichkeit',
    'fr': 'Sensibilité à l\'humidité',
    'it': 'Sensibilità all\'umidità',
  },
  available_colors: {
    'zh-cn': '颜色数量',
    'zh-tw': '顏色數量',
    'en': 'Available Colors',
    'ja': 'カラー展開',
    'ko': '사용 가능한 색상',
    'es': 'Colores disponibles',
    'de': 'Verfügbare Farben',
    'fr': 'Couleurs disponibles',
    'it': 'Colori disponibili',
  },
  spool_weight: {
    'zh-cn': '卷重',
    'zh-tw': '捲重',
    'en': 'Spool Weight',
    'ja': 'スプール重量',
    'ko': '스풀 무게',
    'es': 'Peso del carrete',
    'de': 'Spulengewicht',
    'fr': 'Poids de la bobine',
    'it': 'Peso del rocchetto',
  },
  eco_friendly: {
    'zh-cn': '是否环保',
    'zh-tw': '是否環保',
    'en': 'Eco-Friendly',
    'ja': '環境への配慮',
    'ko': '친환경',
    'es': 'Respetuoso con el medio ambiente',
    'de': 'Umweltfreundlich',
    'fr': 'Écologique',
    'it': 'Eco-compatibile',
  },
  advantage: {
    'zh-cn': '优势',
    'zh-tw': '優勢',
    'en': 'Advantage',
    'ja': 'メリット',
    'ko': '장점',
    'es': 'Ventaja',
    'de': 'Vorteil',
    'fr': 'Avantage',
    'it': 'Vantaggio',
  },

  // ============================================================
  // Thermal
  // ============================================================
  heat_deflection_temperature: {
    'zh-cn': '热变形温度',
    'zh-tw': '熱變形溫度',
    'en': 'Heat Deflection Temperature',
    'ja': '熱たわみ温度',
    'ko': '열변형 온도',
    'es': 'Temperatura de deflexión térmica',
    'de': 'Wärmeformbeständigkeitstemperatur',
    'fr': 'Température de déformation thermique',
    'it': 'Temperatura di deflessione termica',
  },
  glass_transition_temperature: {
    'zh-cn': '玻璃化转变温度',
    'zh-tw': '玻璃化轉變溫度',
    'en': 'Glass Transition Temperature',
    'ja': 'ガラス転移温度',
    'ko': '유리 전이 온도',
    'es': 'Temperatura de transición vítrea',
    'de': 'Glasübergangstemperatur',
    'fr': 'Température de transition vitreuse',
    'it': 'Temperatura di transizione vetrosa',
  },
  vicat_softening_temperature: {
    'zh-cn': '维卡软化温度',
    'zh-tw': '維卡軟化溫度',
    'en': 'Vicat Softening Temperature',
    'ja': 'ビカット軟化温度',
    'ko': '비카트 연화 온도',
    'es': 'Temperatura de ablandamiento Vicat',
    'de': 'Vicat-Erweichungstemperatur',
    'fr': 'Température de ramollissement Vicat',
    'it': 'Temperatura di rammollimento Vicat',
  },
  melting_temperature: {
    'zh-cn': '熔融温度',
    'zh-tw': '熔融溫度',
    'en': 'Melting Temperature',
    'ja': '溶融温度',
    'ko': '용융 온도',
    'es': 'Temperatura de fusión',
    'de': 'Schmelztemperatur',
    'fr': 'Température de fusion',
    'it': 'Temperatura di fusione',
  },
  crystallization_temperature: {
    'zh-cn': '结晶温度',
    'zh-tw': '結晶溫度',
    'en': 'Crystallization Temperature',
    'ja': '結晶化温度',
    'ko': '결정화 온도',
    'es': 'Temperatura de cristalización',
    'de': 'Kristallisationstemperatur',
    'fr': 'Température de cristallisation',
    'it': 'Temperatura di cristallizzazione',
  },
  print_temperature: {
    'zh-cn': '打印温度',
    'zh-tw': '列印溫度',
    'en': 'Print Temperature',
    'ja': '印刷温度',
    'ko': '출력 온도',
    'es': 'Temperatura de impresión',
    'de': 'Drucktemperatur',
    'fr': 'Température d\'impression',
    'it': 'Temperatura di stampa',
  },
  bed_temperature: {
    'zh-cn': '热床温度',
    'zh-tw': '熱床溫度',
    'en': 'Bed Temperature',
    'ja': 'ヒーテッドベッド温度',
    'ko': '베드 온도',
    'es': 'Temperatura de la base',
    'de': 'Druckbetttemperatur',
    'fr': 'Température du plateau',
    'it': 'Temperatura del piano',
  },

  // ============================================================
  // Mechanical (XY direction)
  // ============================================================
  tensile_strength_xy: {
    'zh-cn': '抗拉强度（XY）',
    'zh-tw': '抗拉強度（XY）',
    'en': 'Tensile Strength (XY)',
    'ja': '引張強さ（XY）',
    'ko': '인장 강도 (XY)',
    'es': 'Resistencia a la tracción (XY)',
    'de': 'Zugfestigkeit (XY)',
    'fr': 'Résistance à la traction (XY)',
    'it': 'Resistenza alla trazione (XY)',
  },
  flexural_strength_xy: {
    'zh-cn': '弯曲强度（XY）',
    'zh-tw': '彎曲強度（XY）',
    'en': 'Flexural Strength (XY)',
    'ja': '曲げ強さ（XY）',
    'ko': '굴곡 강도 (XY)',
    'es': 'Resistencia a la flexión (XY)',
    'de': 'Biegefestigkeit (XY)',
    'fr': 'Résistance à la flexion (XY)',
    'it': 'Resistenza alla flessione (XY)',
  },
  flexural_modulus_xy: {
    'zh-cn': '弯曲模量（XY）',
    'zh-tw': '彎曲模量（XY）',
    'en': 'Flexural Modulus (XY)',
    'ja': '曲げ弾性率（XY）',
    'ko': '굴곡 계수 (XY)',
    'es': 'Módulo de flexión (XY)',
    'de': 'Biegemodul (XY)',
    'fr': 'Module de flexion (XY)',
    'it': 'Modulo di flessione (XY)',
  },
  elongation_at_break_xy: {
    'zh-cn': '断裂伸长率（XY）',
    'zh-tw': '斷裂伸長率（XY）',
    'en': 'Elongation at Break (XY)',
    'ja': '破断伸び（XY）',
    'ko': '파단 신장률 (XY)',
    'es': 'Alargamiento a la rotura (XY)',
    'de': 'Bruchdehnung (XY)',
    'fr': 'Allongement à la rupture (XY)',
    'it': 'Allungamento a rottura (XY)',
  },
  impact_strength_xy: {
    'zh-cn': '冲击强度（XY）',
    'zh-tw': '衝擊強度（XY）',
    'en': 'Impact Strength (XY)',
    'ja': '衝撃強さ（XY）',
    'ko': '충격 강도 (XY)',
    'es': 'Resistencia al impacto (XY)',
    'de': 'Schlagfestigkeit (XY)',
    'fr': 'Résistance aux chocs (XY)',
    'it': 'Resistenza agli urti (XY)',
  },
  youngs_modulus_xy: {
    'zh-cn': '杨氏模量（XY）',
    'zh-tw': '楊氏模量（XY）',
    'en': "Young's Modulus (XY)",
    'ja': 'ヤング率（XY）',
    'ko': '영률 (XY)',
    'es': 'Módulo de Young (XY)',
    'de': 'Elastizitätsmodul (XY)',
    'fr': 'Module de Young (XY)',
    'it': 'Modulo di Young (XY)',
  },

  // ============================================================
  // Mechanical (Z direction)
  // ============================================================
  tensile_strength_z: {
    'zh-cn': '抗拉强度（Z）',
    'zh-tw': '抗拉強度（Z）',
    'en': 'Tensile Strength (Z)',
    'ja': '引張強さ（Z）',
    'ko': '인장 강도 (Z)',
    'es': 'Resistencia a la tracción (Z)',
    'de': 'Zugfestigkeit (Z)',
    'fr': 'Résistance à la traction (Z)',
    'it': 'Resistenza alla trazione (Z)',
  },
  flexural_strength_z: {
    'zh-cn': '弯曲强度（Z）',
    'zh-tw': '彎曲強度（Z）',
    'en': 'Flexural Strength (Z)',
    'ja': '曲げ強さ（Z）',
    'ko': '굴곡 강도 (Z)',
    'es': 'Resistencia a la flexión (Z)',
    'de': 'Biegefestigkeit (Z)',
    'fr': 'Résistance à la flexion (Z)',
    'it': 'Resistenza alla flessione (Z)',
  },
  flexural_modulus_z: {
    'zh-cn': '弯曲模量（Z）',
    'zh-tw': '彎曲模量（Z）',
    'en': 'Flexural Modulus (Z)',
    'ja': '曲げ弾性率（Z）',
    'ko': '굴곡 계수 (Z)',
    'es': 'Módulo de flexión (Z)',
    'de': 'Biegemodul (Z)',
    'fr': 'Module de flexion (Z)',
    'it': 'Modulo di flessione (Z)',
  },
  elongation_at_break_z: {
    'zh-cn': '断裂伸长率（Z）',
    'zh-tw': '斷裂伸長率（Z）',
    'en': 'Elongation at Break (Z)',
    'ja': '破断伸び（Z）',
    'ko': '파단 신장률 (Z)',
    'es': 'Alargamiento a la rotura (Z)',
    'de': 'Bruchdehnung (Z)',
    'fr': 'Allongement à la rupture (Z)',
    'it': 'Allungamento a rottura (Z)',
  },
  impact_strength_z: {
    'zh-cn': '冲击强度（Z）',
    'zh-tw': '衝擊強度（Z）',
    'en': 'Impact Strength (Z)',
    'ja': '衝撃強さ（Z）',
    'ko': '충격 강도 (Z)',
    'es': 'Resistencia al impacto (Z)',
    'de': 'Schlagfestigkeit (Z)',
    'fr': 'Résistance aux chocs (Z)',
    'it': 'Resistenza agli urti (Z)',
  },

  // ============================================================
  // Non-directional
  // ============================================================
  tensile_strength: {
    'zh-cn': '抗拉强度',
    'zh-tw': '抗拉強度',
    'en': 'Tensile Strength',
    'ja': '引張強さ',
    'ko': '인장 강도',
    'es': 'Resistencia a la tracción',
    'de': 'Zugfestigkeit',
    'fr': 'Résistance à la traction',
    'it': 'Resistenza alla trazione',
  },
  elongation_at_break: {
    'zh-cn': '断裂伸长率',
    'zh-tw': '斷裂伸長率',
    'en': 'Elongation at Break',
    'ja': '破断伸び',
    'ko': '파단 신장률',
    'es': 'Alargamiento a la rotura',
    'de': 'Bruchdehnung',
    'fr': 'Allongement à la rupture',
    'it': 'Allungamento a rottura',
  },

  // ============================================================
  // Other mechanical
  // ============================================================
  toughness: {
    'zh-cn': '韧性',
    'zh-tw': '韌性',
    'en': 'Toughness',
    'ja': '靭性',
    'ko': '인성',
    'es': 'Tenacidad',
    'de': 'Zähigkeit',
    'fr': 'Ténacité',
    'it': 'Tenacità',
  },
  layer_adhesion: {
    'zh-cn': '层间结合强度',
    'zh-tw': '層間結合強度',
    'en': 'Layer Adhesion',
    'ja': '層間接着力',
    'ko': '층간 결합 강도',
    'es': 'Adhesión entre capas',
    'de': 'Schichthaftung',
    'fr': 'Adhérence entre couches',
    'it': 'Adesione tra gli strati',
  },
};
